actors:
  coela:
    image_url: /images/actors/coela_head.png
    name: coela
    url: https://twitter.com/DRZ400SM
  tadasu:
    image_url: /images/actors/tadasu.jpg
    name: tadasu
    url: https://twitter.com/tadasu443
  soh:
    image_url: /images/actors/soh.png
    name: soh
    url: https://twitter.com/soh__i
  kyon:
    image_url: /images/actors/kyon.jpg
    name: kyon
    url: https://twitter.com/kyonkyonstone
  dessan:
    image_url: /images/actors/dessan.jpg
    name: dessan
    url: https://twitter.com/Dr_Strangedeath
  kotone:
    image_url: /images/actors/kotone.png
    name: kotone
    url: https://twitter.com/kotone_nyt
  nakamura:
    image_url: /images/actors/nakamura.jpg
    name: nakamura
    url: https://researchat.fm/
  shiota:
    image_url: /images/actors/shiota_image.jpg
    name: shiota
    url: https://twitter.com/SHIO_aka_Hitosh
  pome:
    image_url: /images/actors/pome_image.jpg
    name: pome
    url: https://researchat.fm/
  yamaken:
    image_url: /images/actors/yamaken.jpg
    name: yamaken
    url: https://twitter.com/yamaken37
author: researchat
description: Researchat.fmは、バイオロジーの研究者3人がアツいと感じていることを自由に話すポッドキャスト番組です。
description_long: バイオロジーの研究者3人によるポッドキャスト番組です。Vancouver-Boston-山形をつなぎ、その時々アツいと感じたテーマについて研究・論文・技術・ゲーム・漫画など分野を問わず自由に話しています。
email: researchat.fm@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-133831231-1
google-site-verification: b8R8SW8Cg4PQYBFhsLiuXj7FjcSNsYNC8vUxrdnKvPw
hashtag: researchatfm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/researchat-fm/id1453892334?mt=2
keywords: research,science,technology,manga,games
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Researchat.fm
url: https://researchat.fm
